language: python

python:
  - "3.7"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd) 

install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/tests.txt

script:
  - pytest --cov=qstrader/
  - flake8 --ignore E501 tests qstrader

after_success:
  - coveralls
